### ISSUE TITLE
wss:// prefix not working (panics)

### ISSUE THREAD

**Issue by shekohex** [scs/substrate-api-client#104]
I'm trying this simple example:
```rust
use std::convert::TryFrom;

use sp_core::sr25519;
use substrate_api_client::node_metadata;
use substrate_api_client::Api;

fn main() {
    std::env::set_var("RUST_LOG", "debug");
    pretty_env_logger::init_timed();
    let url = "wss://mainnet1.edgewa.re/";
    let api = Api::<sr25519::Pair>::new(url.to_owned());
    let metadata = api.get_metadata();
    let metadata = node_metadata::Metadata::try_from(metadata).unwrap();
    metadata.print_overview();
    metadata.print_modules_with_calls();
    metadata.print_modules_with_events();
}
```
my Cargo.toml
```toml

[dependencies]
substrate-api-client = { git = "https://github.com/scs/substrate-api-client.git" }
log = "0.4"
pretty_env_logger = "0.4"
sp-core = "2.0"
```
but when Running the example I got this error:
```log
 $ cargo -q run
 2020-11-12T13:37:13.005Z INFO  ws > Queuing connection to wss://mainnet1.edgewa.re/
 2020-11-12T13:37:13.012Z DEBUG ws::handshake > Built request from URL:
GET / HTTP/1.1
Connection: Upgrade
Host: mainnet1.edgewa.re:443
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: LQkCkkjAtQ4o5UY4rsKZ3Q==
Upgrade: websocket


 2020-11-12T13:37:13.023Z ERROR ws::handler   > WS Error <Io(Custom { kind: NotConnected, error: "None" })>
 2020-11-12T13:37:13.028Z DEBUG ws::io        > Shutting down websocket client.
 2020-11-12T13:37:13.029Z DEBUG ws::factory   > Factory received WebSocket shutdown request.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', C:\Users\shady\.cargo\git\checkouts\substrate-api-client-9327f54164a9792a\359e776\src\lib.rs:182:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
and here is the verbose logging
```log
$ cargo -q run
 2020-11-12T13:38:41.580Z INFO  ws > Queuing connection to wss://mainnet1.edgewa.re/
 2020-11-12T13:38:41.580Z TRACE ws::io > Running event loop
 2020-11-12T13:38:41.581Z TRACE mio::poll > registering with poller
 2020-11-12T13:38:41.581Z TRACE mio::poll > registering with poller
 2020-11-12T13:38:41.581Z TRACE mio::poll > registering with poller
 2020-11-12T13:38:41.581Z TRACE ws::io    > Waiting for event
 2020-11-12T13:38:41.582Z TRACE mio::sys::windows::selector > select; timeout=Some(0ns)
 2020-11-12T13:38:41.582Z TRACE mio_extras::timer > wakeup thread: sleep_until_tick=18446744073709551615; now_tick=0   
 2020-11-12T13:38:41.582Z TRACE mio::sys::windows::selector > polling IOCP
 2020-11-12T13:38:41.582Z TRACE mio_extras::timer           > sleeping; tick_ms=100; now_tick=0; blocking sleep        
 2020-11-12T13:38:41.582Z TRACE mio::sys::windows::selector > returning
 2020-11-12T13:38:41.583Z TRACE ws::io                      > Processing 1 events
 2020-11-12T13:38:41.589Z TRACE ws::handler                 > Handler is building request to wss://mainnet1.edgewa.re/.
 2020-11-12T13:38:41.590Z DEBUG ws::handshake               > Built request from URL:
GET / HTTP/1.1
Connection: Upgrade
Host: mainnet1.edgewa.re:443
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: tSi6wKvUvaZUlYJAHAvuJg==
Upgrade: websocket


 2020-11-12T13:38:41.597Z TRACE mio::sys::windows::tcp      > cancelling active TCP read
 2020-11-12T13:38:41.597Z TRACE mio::poll                   > registering with poller
 2020-11-12T13:38:41.598Z TRACE mio::sys::windows::selector > register Token(0) Writable
 2020-11-12T13:38:41.599Z TRACE mio::sys::windows::selector > set readiness to Writable
 2020-11-12T13:38:41.607Z TRACE mio::poll                   > registering with poller
 2020-11-12T13:38:41.607Z TRACE ws::io                      > Active connections 1
 2020-11-12T13:38:41.608Z TRACE ws::io                      > Waiting for event
 2020-11-12T13:38:41.608Z TRACE mio::sys::windows::selector > select; timeout=Some(0ns)
 2020-11-12T13:38:41.609Z TRACE mio::sys::windows::selector > polling IOCP
 2020-11-12T13:38:41.610Z TRACE mio::sys::windows::selector > returning
 2020-11-12T13:38:41.610Z TRACE ws::io                      > Processing 1 events
 2020-11-12T13:38:41.611Z TRACE ws::connection              > Ready to write handshake to UNKNOWN.
 2020-11-12T13:38:41.612Z TRACE ws::stream                  > Attempting to write ssl handshake.
 2020-11-12T13:38:41.612Z TRACE mio::sys::windows::selector > set readiness to (empty)
 2020-11-12T13:38:41.613Z TRACE mio::sys::windows::tcp      > scheduling a write of 517 bytes
 2020-11-12T13:38:41.613Z TRACE mio::sys::windows::tcp      > write error: A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied. (os error 10057)
 2020-11-12T13:38:41.615Z TRACE mio::sys::windows::selector > set readiness to Writable
 2020-11-12T13:38:41.615Z TRACE ws::io                      > Scheduling connection to UNKNOWN as Readable
 2020-11-12T13:38:41.615Z TRACE mio::poll                   > registering with poller
 2020-11-12T13:38:41.626Z TRACE mio::sys::windows::selector > reregister Token(0) Readable
 2020-11-12T13:38:41.626Z TRACE mio::sys::windows::selector > set readiness to Writable
 2020-11-12T13:38:41.627Z TRACE mio::sys::windows::tcp      > scheduling a read
 2020-11-12T13:38:41.627Z TRACE mio::sys::windows::selector > set readiness to Readable | Writable
 2020-11-12T13:38:41.628Z TRACE ws::io                      > Active connections 1
 2020-11-12T13:38:41.628Z TRACE ws::io                      > Waiting for event
 2020-11-12T13:38:41.629Z TRACE mio::sys::windows::selector > select; timeout=Some(0ns)
 2020-11-12T13:38:41.630Z TRACE mio::sys::windows::selector > polling IOCP
 2020-11-12T13:38:41.631Z TRACE mio::sys::windows::selector > returning
 2020-11-12T13:38:41.631Z TRACE ws::io                      > Processing 1 events
 2020-11-12T13:38:41.632Z TRACE ws::connection              > Performing TLS negotiation on UNKNOWN.
 2020-11-12T13:38:41.632Z TRACE ws::connection              > Ready to write handshake to UNKNOWN.
 2020-11-12T13:38:41.643Z TRACE ws::stream                  > Attempting to write ssl handshake.
 2020-11-12T13:38:41.645Z TRACE mio::sys::windows::selector > set readiness to Writable
 2020-11-12T13:38:41.649Z TRACE mio::sys::windows::tcp      > scheduling a read
 2020-11-12T13:38:41.659Z TRACE mio::sys::windows::selector > set readiness to Readable | Writable
 2020-11-12T13:38:41.660Z TRACE ws::io                      > Encountered error while reading: None
 2020-11-12T13:38:41.661Z ERROR ws::handler                 > WS Error <Io(Custom { kind: NotConnected, error: "None" })>
 2020-11-12T13:38:41.662Z TRACE ws::io                      > WebSocket connection to token=Token(0) disconnected.
 2020-11-12T13:38:41.663Z TRACE ws::io                      > Active connections 0
 2020-11-12T13:38:41.663Z DEBUG ws::io                      > Shutting down websocket client.
 2020-11-12T13:38:41.664Z DEBUG ws::factory                 > Factory received WebSocket shutdown request.
 2020-11-12T13:38:41.664Z TRACE mio::poll                   > deregistering handle with poller
 2020-11-12T13:38:41.664Z TRACE mio::poll                   > deregistering handle with poller
 2020-11-12T13:38:41.665Z TRACE mio::poll                   > deregistering handle with poller
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', C:\Users\shady\.cargo\git\checkouts\substrate-api-client-9327f54164a9792a\359e776\src\lib.rs:182:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I saw that the last commit in master says that fixed `wss://` problem but I guess it still there or do I miss something?

**Comment by clangenb** [comment]
I believe you are simply missing the port. The standard port for `wss` is 443.

**Comment by clangenb** [comment]
your url would be in the stand case: `let url = "wss://mainnet1.edgewa.re:433";`

**Comment by shekohex** [comment]
unfortunately, there is no change, same problem :(

**Comment by brenzi** [comment]
Ok, I just verified that js-apps can connect correctly. Have you done a cargo update? I would recommend to use tags in your toml file if referencing git crates. 
There has been a wss fix recently 359e7769486479b77c8f9df198eeea36d5995825 so you'll want this release:
https://github.com/scs/substrate-api-client/releases/tag/v0.4.10-sub2.0.0

does edgeware depend on the substrate 2.0.0 release?

**Comment by brenzi** [comment]
If I run our example on it, it works:
```
./target/release/examples/example_print_metadata -u wss://mainnet1.edgewa.re -p 443
```

**Comment by brenzi** [comment]
@shekohex does it work with above hints?

**Comment by shekohex** [comment]
I ended up using `substrate-subxt` 😶
I will try again using this library too.
