### ISSUE TITLE
template module get bad signature transaction

### ISSUE THREAD

**Issue by zqhxuyuan** [scs/substrate-api-client#159]
I add template module like balances to call do_something(1), the api client example get:
```
[+] Alice's Account Nonce is 0
account:88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee (5FA9nQDV...)
payload:[222, 101, 229, 233, 132, 208, 13, 84, 2, 10, 115, 162, 59, 142, 145, 209, 20, 132, 34, 162, 166, 166, 142, 80, 242, 175, 243, 93, 214, 63, 114, 54]
[+] Composed extrinsic: UncheckedExtrinsic(Some((MultiAddress::Id(88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee (5FA9nQDV...)), GenericExtra(Era::Immortal, 0, 0))), ([9, 0], MultiAddress::Id(88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee (5FA9nQDV...)), 1))

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHexString(InvalidStringLength)', src/examples/example_template_ed25519.rs:44:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-09-09T07:37:38Z ERROR ws::handler] WS Error <Custom(Extrinsic("extrinsic error code 1010: Invalid Transaction: Transaction has a bad signature"))>
```

and the node template logs:
```
2021-09-09 15:37:38 UncheckedExtrinsic:UncheckedExtrinsic(Some((MultiAddress::Id(88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee (5FA9nQDV...)), (CheckSpecVersion, CheckTxVersion, CheckGenesis, CheckMortality(Era::Immortal), CheckNonce(0), CheckWeight, ChargeTransactionPayment<0>))), Call::TemplateModule(Call::do_something(886867968)))
2021-09-09 15:37:38 payload:[253, 193, 211, 124, 230, 225, 239, 10, 203, 212, 53, 196, 164, 113, 123, 22, 149, 109, 151, 96, 195, 10, 167, 238, 58, 118, 152, 239, 7, 234, 74, 25]
2021-09-09 15:37:38 Failed to submit extrinsic: Transaction pool error: Invalid transaction validity: InvalidTransaction::BadProof
```

from the log above, the payload is not the same. If I use balance transfer, the payload log is same.

> the payload is: BlakeTwo256::hash_of(&payload).as_fixed_bytes() just add to both side.

As I check the call parameter of node template and api-client, I found 
- node template: Call::do_something(886867968) 
- api-client: 1

![image](https://user-images.githubusercontent.com/1088525/132645615-3fd12de6-d211-4522-b640-6d45ea3096bf.png)

is that cause payload different, and finally cause invalid transaction?

Ps: I tried add another method: do_something0() which has only origin parameter, and still get this problem which has two different payload.
```
2021-09-09 16:05:44 UncheckedExtrinsic:UncheckedExtrinsic(Some((MultiAddress::Id(88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee (5FA9nQDV...)), (CheckSpecVersion, CheckTxVersion, CheckGenesis, CheckMortality(Era::Immortal), CheckNonce(0), CheckWeight, ChargeTransactionPayment<0>))), Call::TemplateModule(Call::do_something0))
2021-09-09 16:05:44 payload:[224, 246, 130, 186, 144, 241, 4, 79, 204, 165, 80, 238, 210, 196, 151, 208, 67, 175, 54, 55, 174, 183, 164, 71, 226, 54, 237, 168, 65, 186, 239, 13]
2021-09-09 16:05:44 Failed to submit extrinsic: Transaction pool error: Invalid transaction validity: InvalidTransaction::BadProof
```

```
[+] Alice's Account Nonce is 0
account:88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee (5FA9nQDV...)
payload:[63, 140, 83, 62, 66, 232, 50, 25, 205, 114, 92, 35, 176, 48, 44, 94, 140, 160, 136, 28, 2, 222, 10, 28, 138, 175, 85, 89, 90, 133, 216, 7]
[+] Composed extrinsic: UncheckedExtrinsic(Some((MultiAddress::Id(88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee (5FA9nQDV...)), GenericExtra(Era::Immortal, 0, 0))), ([9, 1], MultiAddress::Id(88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee (5FA9nQDV...))))

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHexString(InvalidStringLength)', src/examples/example_template_ed25519.rs:45:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-09-09T08:05:44Z ERROR ws::handler] WS Error <Custom(Extrinsic("extrinsic error code 1010: Invalid Transaction: Transaction has a bad signature"))>
```

**Comment by zqhxuyuan** [comment]
solved. the parameter is not right.
