### ISSUE TITLE
examples fail: example_transfer / _get_storage / _contract 

### ISSUE THREAD

**Issue by brenzi** [scs/substrate-api-client#20]
```
Interacting with node on 127.0.0.1:9944

[+] Bob's Free Balance is is 1152921504606846976

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHexCharacter { c: 'n', index: 0 }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
debug
```
[2019-09-16T20:18:11Z INFO  substrate_api_client::rpc::client] sending request: {"id":"1","jsonrpc":"2.0","method":"state_getStorage","params":["0x5c54163a1c72509b5250f0a30b9001fdee9d9b48388b06921f1b210e81e3a1f0"]}
[2019-09-16T20:18:11Z DEBUG ws::handler] Handler received: 
<FRAME>
final: true
reserved: false false false
opcode: TEXT
length: 42
payload length: 40
payload: 0x7b226a736f6e727063223a22322e30222c22726573756c74223a6e756c6c2c226964223a2231227d
            
[2019-09-16T20:18:11Z INFO  substrate_api_client::rpc::client] got message
[2019-09-16T20:18:11Z DEBUG substrate_api_client::rpc::client] {"jsonrpc":"2.0","result":null,"id":"1"}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHexCharacter { c: 'n', index: 0 }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[2019-09-16T20:18:11Z DEBUG ws::handler] Handler received: 
<FRAME>
final: true
reserved: false false false
opcode: CLOSE
length: 4
payload length: 2
payload: 0x3e8
```

reproduce:
run against master : https://github.com/scs/substrate-test-nodes
```
./target/release/substrate-test-node purge-chain --dev
./target/release/substrate-test-node --dev
```

then
```
cargo run --example example_transfer 
```

is error handling missing in case of returning a `null` value?

**Comment by clangenb** [comment]
You were right error handling was missing in those functions. The from hexstr functions do now return a Result.

Purge-chain was neccessary to trigger the error. Apparently, the first AccountNonce is `null` instead of `0`.
