### ISSUE TITLE
Unable to import sr25519 in the node metadata example

### ISSUE THREAD

**Issue by kebab-mai-haddi** [scs/substrate-api-client#55]
Hi, with the minimal setup that you have defined in the tutorial:
```
use substrate_api_client::{node_metadata, Api};

fn main() {
    // instantiate an Api that connects to the given address
    let url = "127.0.0.1:9944";
    // if no signer is set in the whole program, we need to give to Api a specific type instead of an associated type
    // as during compilation the type needs to be defined.
    let api = Api::<sr25519::Pair>::new(format!("ws://{}", url));

    let meta = api.get_metadata();
    println!(
        "Metadata:\n {}",
        node_metadata::pretty_format(&meta).unwrap()
    );
}

```

and 
```
[package]
name = "api-client-tutorial"
version = "0.1.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
substrate-api-client = { git = "https://github.com/scs/substrate-api-client.git" }
```

I am getting many errors:
```
➜  api-client-tutorial git:(master) ✗ cargo run
   Compiling api-client-tutorial v0.1.0 (/Users/aviralsrivastava/dev/api-client-tutorial)
error[E0433]: failed to resolve: use of undeclared type or module `sr25519`
 --> src/main.rs:8:21
  |
8 |     let api = Api::<sr25519::Pair>::new(format!("ws://{}", url));
  |                     ^^^^^^^ use of undeclared type or module `sr25519`

error[E0425]: cannot find function `pretty_format` in module `node_metadata`
  --> src/main.rs:13:24
   |
13 |         node_metadata::pretty_format(&meta).unwrap()
   |                        ^^^^^^^^^^^^^ not found in `node_metadata`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0425, E0433.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `api-client-tutorial`.

To learn more, run the command again with --verbose.
```

**Comment by brenzi** [comment]
It looks like our tutorial is outdated. Please look at [this example](https://github.com/scs/substrate-api-client/blob/master/src/examples/example_print_metadata.rs)

**Comment by kebab-mai-haddi** [comment]
@brenzi 
I am sorry but this hasn't been helpful. You should have provided the corresponding dependencies' source as well.

**Comment by kebab-mai-haddi** [comment]
For instance, I literally copied the Cargo.toml file and still, I am getting following error from the link that you referenced:

```
➜  api-client-tutorial git:(master) ✗ cargo run
   Compiling substrate-api-client v2.0.0 (/Users/aviralsrivastava/dev/api-client-tutorial)
error[E0433]: failed to resolve: use of undeclared type or module `substrate_api_client`
 --> src/main.rs:9:5
  |
9 | use substrate_api_client::node_metadata::Metadata;
  |     ^^^^^^^^^^^^^^^^^^^^ use of undeclared type or module `substrate_api_client`

error[E0432]: unresolved import `clap`
 --> src/main.rs:6:5
  |
6 | use clap::App;
  |     ^^^^ use of undeclared type or module `clap`

error[E0432]: unresolved import `substrate_api_client`
  --> src/main.rs:10:5
   |
10 | use substrate_api_client::Api;
   |     ^^^^^^^^^^^^^^^^^^^^ use of undeclared type or module `substrate_api_client`

error[E0433]: failed to resolve: use of undeclared type or module `Metadata`
  --> src/main.rs:20:16
   |
20 |     let meta = Metadata::try_from(api.get_metadata()).unwrap();
   |                ^^^^^^^^ use of undeclared type or module `Metadata`

error[E0433]: failed to resolve: use of undeclared type or module `Metadata`
  --> src/main.rs:28:9
   |
28 |         Metadata::pretty_format(&api.get_metadata()).unwrap_or("pretty format failed".to_string())
   |         ^^^^^^^^ use of undeclared type or module `Metadata`

warning: unused import: `std::convert::TryFrom`
 --> src/main.rs:4:5
  |
4 | use std::convert::TryFrom;
  |     ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `substrate-api-client`.

To learn more, run the command again with --verbose.
```

**Comment by brenzi** [comment]
can you point me to your code repo so I can have a look?

**Comment by kebab-mai-haddi** [comment]
Hey, thanks for reverting. 
I am using the master code only. https://github.com/kebab-mai-haddi/substrate-api-client

**Comment by clangenb** [comment]
Sorry I cannot reproduce. When I check out your repo (which is up-to-date with our master), I can do:
* cd tutorials/api-client-tutorial
* cargo run

and it works.

or I can go to the root directory and do:
* cargo build --example example_print_metada

and it works too, what steps do you perform for it to fail?

**Comment by kebab-mai-haddi** [comment]
I was at the root directory: `/Users/aviralsrivastava/dev/substrate-api-client`. I ran the command: `cargo run --example example_get_storage`. And got the following error:
```
     Running `target/debug/examples/example_get_storage`
Interacting with node on 127.0.0.1:9944

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("Error decoding field RuntimeMetadataPrefixed.1")', /Users/aviralsrivastava/dev/substrate-api-client/src/lib.rs:143:9
stack backtrace:
   0:        0x103e0860f - backtrace::backtrace::libunwind::trace::h46cd1629179eb2bb
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:        0x103e0860f - backtrace::backtrace::trace_unsynchronized::he6a2c6978474c69f
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:        0x103e0860f - std::sys_common::backtrace::_print_fmt::h7e4f94659b124684
                               at src/libstd/sys_common/backtrace.rs:78
   3:        0x103e0860f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h87f791d1934b5da0
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x103e279ce - core::fmt::write::h23c8f27116676cdf
                               at src/libcore/fmt/mod.rs:1063
   5:        0x103e02367 - std::io::Write::write_fmt::h1f00d7a43839acf0
                               at src/libstd/io/mod.rs:1426
   6:        0x103e0a64a - std::sys_common::backtrace::_print::hdb601a5265ba7f34
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x103e0a64a - std::sys_common::backtrace::print::h5b8116376026eccf
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x103e0a64a - std::panicking::default_hook::{{closure}}::hf26168ecfd2fc8c1
                               at src/libstd/panicking.rs:204
   9:        0x103e0a38c - std::panicking::default_hook::hf7eb684688e3f257
                               at src/libstd/panicking.rs:224
  10:        0x103e0ad28 - std::panicking::rust_panic_with_hook::hba1377a258e49bd5
                               at src/libstd/panicking.rs:470
  11:        0x103e0a8c2 - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:        0x103e2607f - core::panicking::panic_fmt::h0d0a3efb6be37d9e
                               at src/libcore/panicking.rs:111
  13:        0x103e25ec5 - core::option::expect_none_failed::h60a7fb6522066a05
                               at src/libcore/option.rs:1211
  14:        0x10379cd8f - core::result::Result<T,E>::unwrap::hdd8502f143ffb0a4
                               at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libcore/result.rs:1003
  15:        0x1037b4b41 - substrate_api_client::Api<P>::_get_metadata::ha78d45a48b715fcc
                               at /Users/aviralsrivastava/dev/substrate-api-client/src/lib.rs:143
  16:        0x1037b52df - substrate_api_client::Api<P>::new::h191709ce62e4fbff
                               at /Users/aviralsrivastava/dev/substrate-api-client/src/lib.rs:102
  17:        0x1037b6ad4 - example_get_storage::main::hbbbe92adf2e40cca
                               at src/examples/example_get_storage.rs:28
  18:        0x1037b407e - std::rt::lang_start::{{closure}}::hb893d0bed7d75aad
                               at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libstd/rt.rs:67
  19:        0x103e0a788 - std::rt::lang_start_internal::{{closure}}::h97c2f4abbac12fe2
                               at src/libstd/rt.rs:52
  20:        0x103e0a788 - std::panicking::try::do_call::hd39a46c6642b6b7f
                               at src/libstd/panicking.rs:303
  21:        0x103e0d6bb - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  22:        0x103e0b12a - std::panicking::try::hd7941e20369365bb
                               at src/libstd/panicking.rs:281
  23:        0x103e0b12a - std::panic::catch_unwind::hb0089eff0d0a17f8
                               at src/libstd/panic.rs:394
  24:        0x103e0b12a - std::rt::lang_start_internal::h74a2f48667b795db
                               at src/libstd/rt.rs:51
  25:        0x1037b4061 - std::rt::lang_start::h9de3795ff5e19923
                               at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libstd/rt.rs:67
  26:        0x1037b7622 - example_get_storage::get_node_url_from_cli::h28ef078e74cb1bea
```

**Comment by kebab-mai-haddi** [comment]
@brenzi 
And I ran the exact commands that you posted, again got the same error:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("Error decoding field RuntimeMetadataPrefixed.1")', /Users/aviralsrivastava/dev/substrate-api-client/src/lib.rs:143:9
stack backtrace:`

Btw, I am running the substrate node from the official documentation.

**Comment by clangenb** [comment]
this is most likely due to an incompatible node.

Check that the node you are using has the same substrate revision as the `substrate-api-client`'s

**Comment by kebab-mai-haddi** [comment]
How can I do that?

**Comment by clangenb** [comment]
got to your local substrate repo and do:

git checkout 00a400f82539e2f78e8ddbcd98aea512c87c5f3c

this is already the correct commit

**Comment by kebab-mai-haddi** [comment]
In fact, when running the test node from this repo(as suggested in this repo), it shows error.
Steps:
```
git clone https://github.com/scs/substrate-test-nodes
cd substrate-test-nodes/
git checkout api-M1.1
cargo build --release
```
Error:
```
error[E0432]: unresolved import `hashbrown`
  --> /Users/aviralsrivastava/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmi-validation-0.1.0/src/lib.rs:31:5
   |
31 | use hashbrown::HashSet;
   |     ^^^^^^^^^ use of undeclared type or module `hashbrown`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `wasmi-validation`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by clangenb** [comment]
ups, thanks for pointing this out. The readme is old ckeckout master.

**Comment by kebab-mai-haddi** [comment]
Also, going into the local substrate repo:
```
git clone github.com/substrate-developer-hub/substrate-package
cd substrate-package
git checkout 00a400f82539e2f78e8ddbcd98aea512c87c5f3c
```
I got the error:
```
fatal: reference is not a tree: 00a400f82539e2f78e8ddbcd98aea512c87c5f3c
```

**Comment by kebab-mai-haddi** [comment]
>ups, thanks for pointing this out. The readme is old ckeckout master.

Welcome, but I didn't get this: "The readme is old ckeckout master."

**Comment by clangenb** [comment]
Ah sorry. I did not know that you were using that repository. The substrate version they are using is too old. you would need to use https://github.com/paritytech/substrate

and regarding our test-node you need to do:

git clone https://github.com/scs/substrate-test-nodes
cd substrate-test-nodes/
cargo build --release

do not do: git checkout api-M1.1

if you already did, do: git checkout master
and then build it.

I won't be answering further questions today, I am going home. :)

**Comment by kebab-mai-haddi** [comment]
@brenzi @clangenb 
It worked.

Thanks guys!
